'use client'

import Link from 'next/link'
import { ArrowLeft, Plus, Search, Trash2, Check, StickyNote, Landmark, Users, Activity, Calculator, Ticket, Smartphone, ShieldCheck, FileText, Zap, Bot, Database, Camera, Puzzle } from 'lucide-react'
import { useMemo, useState } from 'react'

const names: Record<string,string> = { notes:'Notes','file-kerja-cs':'File Kerja CS','cs-dashboard':'CS Dashboard','ai-chat':'AI Chat','prediksi-togel':'Prediksi Togel','hasil-result-togel':'Hasil Result Togel','kalkulator-togel':'Kalkulator Togel','kpbi-live':'KPBI Live','kpbi-cek-member':'KPBI Cek Member','kalkulator-betting':'Kalkulator Betting','kalkulator-parlay':'Kalkulator Parlay','kode-tiket':'Kode Tiket','hitung-freespin':'Hitung Freespin','tangkapan-menang':'Tangkapan Menang','profil-bank':'Profil Bank','rrn-qris':'RRN QRIS','pintasan-bqris':'Pintasan B.QRIS','validasi-rekening':'Validasi Rekening','data-depo-wd-qris':'Data Depo / WD QRIS','alat-kerja':'Alat Kerja','filter-kode-game':'Filter Kode Game','chat-koordinasi':'Chat Koordinasi','arsip-kesalahan-chat':'Arsip Kesalahan Chat','pengguna-online':'Pengguna Online','pengguna-akses':'Pengguna & Akses','activity-log':'Activity Log','pengaturan':'Pengaturan','auto-screenshot':'Auto Screenshot','extension-suite':'Extension Suite' }

type Note={id:number;title:string;content:string}

const csFeatures = [
 {title:'Pusat Kendali Bank',desc:'SOP, mutasi, kasus minus/plus, dan status operasional bank.',icon:Landmark,href:'/modules/profil-bank'},
 {title:'File Kerja CS',desc:'Akses pusat file dan dokumen kerja customer service.',icon:FileText,href:'/modules/file-kerja-cs'},
 {title:'Prediksi & Result',desc:'Pusat alat prediksi, hasil result, dan kalkulator terkait.',icon:Activity,href:'/modules/prediksi-togel'},
 {title:'Kalkulator Betting',desc:'Perhitungan betting dan parlay dalam satu workspace.',icon:Calculator,href:'/modules/kalkulator-betting'},
 {title:'Tiket & Freespin',desc:'Kode tiket, hitung freespin, dan tangkapan kemenangan.',icon:Ticket,href:'/modules/kode-tiket'},
 {title:'QRIS & Rekening',desc:'RRN QRIS, pintasan B.QRIS, dan validasi rekening.',icon:ShieldCheck,href:'/modules/rrn-qris'},
 {title:'Alat Kerja',desc:'Perangkat kerja CS dan pengecekan operasional.',icon:Smartphone,href:'/modules/alat-kerja'},
 {title:'Tim & Activity',desc:'Chat koordinasi, user online, akses, dan activity log.',icon:Users,href:'/modules/chat-koordinasi'},
 {title:'AI Assistant',desc:'Workspace AI Chat untuk membantu pekerjaan harian.',icon:Bot,href:'/modules/ai-chat'},
 {title:'Data Depo / WD',desc:'Pusat data transaksi Depo dan WD QRIS.',icon:Database,href:'/modules/data-depo-wd-qris'},
 {title:'Auto Screenshot',desc:'Kontrol dan pengelolaan tangkapan layar kerja.',icon:Camera,href:'/modules/auto-screenshot'},
 {title:'Extension Suite',desc:'Kumpulan utilitas browser untuk workflow CS.',icon:Puzzle,href:'/modules/extension-suite'},
]

export default function ModuleClient({slug}:{slug:string}){
 const name=names[slug] ?? slug.replaceAll('-',' ')
 const [notes,setNotes]=useState<Note[]>([]); const [title,setTitle]=useState(''); const [content,setContent]=useState(''); const [query,setQuery]=useState('')
 const isNotes=slug==='notes'; const isCs=slug==='cs-dashboard'||slug==='file-kerja-cs'; const filtered=useMemo(()=>notes.filter(n=>(n.title+' '+n.content).toLowerCase().includes(query.toLowerCase())),[notes,query])
 const add=()=>{if(!title.trim()&&!content.trim())return;setNotes(v=>[{id:Date.now(),title:title.trim()||'Catatan Baru',content:content.trim()},...v]);setTitle('');setContent('')}
 const remove=(id:number)=>setNotes(v=>v.filter(n=>n.id!==id))
 return <main className="min-h-screen bg-[#040d18] p-5 sm:p-8 lg:p-12"><div className="page-enter mx-auto max-w-6xl"><Link href="/" className="menu-item inline-flex items-center gap-2 px-3 py-2 text-sm text-slate-400"><ArrowLeft size={16}/> Kembali ke Dashboard</Link>
 {isNotes?<><div className="mt-7 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-xs tracking-[.2em] text-cyan-500">D.KERJA / CATATAN</div><h1 className="mt-2 text-3xl font-bold">Notes</h1><p className="mt-2 text-sm text-slate-500">Catat informasi kerja dengan cepat.</p></div><div className="text-xs text-slate-500">{notes.length} catatan</div></div><div className="mt-6 grid gap-5 lg:grid-cols-[380px_1fr]"><section className="rounded-2xl border border-[#183047] bg-[#08182a] p-5"><div className="flex items-center gap-2 font-semibold"><StickyNote size={18} className="text-cyan-400"/> Catatan Baru</div><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Judul catatan" className="mt-5 w-full rounded-xl border border-[#183047] bg-[#071726] px-4 py-3 text-sm outline-none focus:border-cyan-800"/><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="Tulis catatan..." rows={8} className="mt-3 w-full resize-none rounded-xl border border-[#183047] bg-[#071726] px-4 py-3 text-sm outline-none focus:border-cyan-800"/><button onClick={add} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-cyan-800 bg-cyan-950/40 px-4 py-3 text-sm text-cyan-300 transition hover:bg-cyan-900/30"><Plus size={17}/> Simpan Catatan</button></section><section className="rounded-2xl border border-[#183047] bg-[#08182a] p-5"><div className="relative"><Search size={16} className="absolute left-3 top-3.5 text-slate-600"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari catatan..." className="w-full rounded-xl border border-[#183047] bg-[#071726] py-3 pl-10 pr-4 text-sm outline-none focus:border-cyan-800"/></div><div className="mt-4 space-y-3">{filtered.length===0?<div className="rounded-xl border border-dashed border-[#214258] p-8 text-center text-sm text-slate-600">Belum ada catatan.</div>:filtered.map(n=><article key={n.id} className="card-enter rounded-xl border border-[#183047] bg-[#071726] p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-medium">{n.title}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-500">{n.content||'Tidak ada isi.'}</p></div><button onClick={()=>remove(n.id)} className="rounded-lg p-2 text-slate-600 transition hover:bg-red-500/10 hover:text-red-400"><Trash2 size={16}/></button></div><div className="mt-3 flex items-center gap-1 text-[10px] text-emerald-500"><Check size={12}/> Tersimpan di sesi ini</div></article>)}</div></section></div></>
 :isCs?<><div className="mt-7"><div className="text-xs font-semibold tracking-[.2em] text-cyan-500">D.KERJA / CS WORKSPACE</div><div className="mt-2 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-bold">CS Dashboard</h1><p className="mt-2 text-sm text-slate-500">Pusat kendali pekerjaan CS, bank, transaksi, tools, dan koordinasi tim.</p></div><div className="rounded-xl border border-emerald-900/60 bg-emerald-950/20 px-4 py-2 text-xs text-emerald-400">● Sistem Online</div></div></div><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{csFeatures.map((f,i)=>{const Icon=f.icon;return <Link key={f.title} href={f.href} className="card-enter menu-item rounded-2xl border border-[#183047] bg-[#08182a] p-5" style={{animationDelay:`${i*45}ms`}}><div className="flex items-start gap-4"><div className="grid size-11 shrink-0 place-items-center rounded-xl border border-[#214258] bg-[#092235] text-cyan-400"><Icon size={19}/></div><div><h2 className="font-semibold">{f.title}</h2><p className="mt-1.5 text-xs leading-5 text-slate-500">{f.desc}</p><span className="mt-3 inline-flex items-center gap-1 text-[11px] text-cyan-400">Buka modul <Zap size={12}/></span></div></div></Link>})}</div><div className="mt-6 rounded-2xl border border-[#183047] bg-[#08182a] p-5"><div className="flex items-center gap-2 font-semibold"><Landmark size={17} className="text-cyan-400"/> Struktur sumber yang dipetakan</div><p className="mt-2 text-xs leading-5 text-slate-500">Bundle dashboard CS yang kamu kirim berisi modul bank center, notes, file CS, togel, kalkulator, tiket, QRIS, tim, auto screenshot, dan extension suite. Modul yang cocok sudah dipetakan ke navigasi D.KERJA tanpa memasukkan Money Tracking.</p></div></>
 :<section className="mt-6 rounded-2xl border border-[#183047] bg-[#08182a] p-8"><div className="text-xs tracking-[.2em] text-cyan-500">D.KERJA MODULE</div><h1 className="mt-2 text-3xl font-bold capitalize">{name}</h1><p className="mt-3 max-w-xl text-sm leading-6 text-slate-500">Workspace modul sudah aktif. Fitur khusus dapat dikembangkan di halaman ini tanpa mengubah dashboard utama.</p><div className="mt-7 rounded-xl border border-dashed border-[#214258] bg-[#071726] p-5 text-sm text-slate-400">Workspace <span className="text-cyan-400">ready</span>.</div></section>}</div></main>
}
