'use client'

import Link from 'next/link'
import { useState } from 'react'
import { Activity, Bot, Calculator, ChevronDown, ClipboardList, FileText, Gamepad2, Hash, Home, Landmark, LayoutDashboard, Menu, Settings, ShieldCheck, Ticket, Users, Wrench, X } from 'lucide-react'

type MenuItem = readonly [string, string]
type MenuSection = { title: string; items: MenuItem[] }

const sections: MenuSection[] = [
  { title: 'DASHBOARD', items: [['Overview','/']] },
  { title: 'CATATAN', items: [['Notes','/modules/notes'], ['File Kerja CS','/modules/file-kerja-cs']] },
  { title: 'AI ASSISTANT', items: [['AI Chat','/modules/ai-chat']] },
  { title: 'TOGEL', items: [['Prediksi Togel','/modules/prediksi-togel'], ['Hasil Result Togel','/modules/hasil-result-togel'], ['Kalkulator Togel','/modules/kalkulator-togel'], ['KPBI Live','/modules/kpbi-live'], ['KPBI Cek Member','/modules/kpbi-cek-member']] },
  { title: 'KALKULATOR', items: [['Kalkulator Betting','/modules/kalkulator-betting'], ['Kalkulator Parlay','/modules/kalkulator-parlay']] },
  { title: 'TIKET & FREESPIN', items: [['Kode Tiket','/modules/kode-tiket'], ['Hitung Freespin','/modules/hitung-freespin'], ['Tangkapan Menang','/modules/tangkapan-menang']] },
  { title: 'BANK & QRIS', items: [['Profil Bank','/modules/profil-bank'], ['RRN QRIS','/modules/rrn-qris'], ['Pintasan B.QRIS','/modules/pintasan-bqris'], ['Validasi Rekening','/modules/validasi-rekening']] },
  { title: 'DATA DEPO / WD QRIS', items: [['Data Depo / WD QRIS','/modules/data-depo-wd-qris']] },
  { title: 'ALAT KERJA', items: [['Alat Kerja','/modules/alat-kerja']] },
  { title: 'KODE GAME', items: [['Filter Kode Game','/modules/filter-kode-game']] },
  { title: 'TIM', items: [['Chat Koordinasi','/modules/chat-koordinasi'], ['Arsip Kesalahan Chat','/modules/arsip-kesalahan-chat'], ['Pengguna Online','/modules/pengguna-online'], ['Pengguna & Akses','/modules/pengguna-akses'], ['Activity Log','/modules/activity-log']] },
  { title: 'SISTEM', items: [['Pengaturan','/modules/pengaturan'], ['Auto Screenshot','/modules/auto-screenshot'], ['Extension Suite','/modules/extension-suite']] },
]

const icons: Record<string, any> = { Overview:LayoutDashboard, Notes:FileText, 'File Kerja CS':ClipboardList, 'AI Chat':Bot, 'Prediksi Togel':Hash, 'Hasil Result Togel':Hash, 'Kalkulator Togel':Calculator, 'KPBI Live':Activity, 'KPBI Cek Member':ShieldCheck, 'Kalkulator Betting':Calculator, 'Kalkulator Parlay':Calculator, 'Kode Tiket':Ticket, 'Hitung Freespin':Calculator, 'Tangkapan Menang':ClipboardList, 'Profil Bank':Landmark, 'RRN QRIS':Hash, 'Pintasan B.QRIS':Home, 'Validasi Rekening':ShieldCheck, 'Data Depo / WD QRIS':ClipboardList, 'Alat Kerja':Wrench, 'Filter Kode Game':Gamepad2, 'Chat Koordinasi':Users, 'Arsip Kesalahan Chat':FileText, 'Pengguna Online':Activity, 'Pengguna & Akses':Users, 'Activity Log':Activity, Pengaturan:Settings, 'Auto Screenshot':ClipboardList, 'Extension Suite':Wrench }

export default function Dashboard() {
  const [active, setActive] = useState('Overview'); const [mobileOpen, setMobileOpen] = useState(false); const [collapsed, setCollapsed] = useState<Record<string, boolean>>({})
  return <div className="min-h-screen bg-[#040d18] text-slate-200">
    <header className="fixed inset-x-0 top-0 z-30 h-16 border-b border-[#183047] bg-[#061426]/95 backdrop-blur-xl flex items-center justify-between px-4 lg:pl-[292px]"><div className="flex items-center gap-3"><button onClick={()=>setMobileOpen(!mobileOpen)} className="lg:hidden rounded-lg border border-[#183047] p-2">{mobileOpen?<X size={18}/>:<Menu size={18}/>}</button><div><div className="font-semibold tracking-wide">{active}</div><div className="text-xs text-slate-500">D.KERJA / Workspace</div></div></div><div className="flex items-center gap-3"><div className="hidden sm:block text-right"><div className="text-sm font-medium">RIZKY</div><div className="text-[10px] text-cyan-400">SUPER MASTER</div></div><div className="grid size-9 place-items-center rounded-full border border-cyan-900 bg-[#092235] text-cyan-300">R</div></div></header>
    <aside className={`${mobileOpen?'translate-x-0':'-translate-x-full'} lg:translate-x-0 fixed z-40 top-0 bottom-0 left-0 w-[276px] border-r border-[#183047] bg-[#061426] transition-transform duration-300 overflow-y-auto`}><div className="sticky top-0 z-10 border-b border-[#183047] bg-[#061426] p-5"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl border border-cyan-900 bg-[#092235] text-cyan-300"><LayoutDashboard size={21}/></div><div><div className="font-bold tracking-[.18em]">D.KERJA</div><div className="text-[10px] text-slate-500 tracking-[.22em]">ENTERPRISE SUITE</div></div></div></div><nav className="p-3 space-y-4">{sections.map(section=><div key={section.title}><button onClick={()=>setCollapsed(v=>({...v,[section.title]:!v[section.title]}))} className="w-full px-2 mb-1 flex items-center justify-between text-[10px] font-semibold tracking-[.18em] text-slate-600 hover:text-slate-400"><span>{section.title}</span><ChevronDown size={13} className={`${collapsed[section.title]?' -rotate-90':''} transition-transform`}/></button>{!collapsed[section.title]&&<div className="space-y-1">{section.items.map(([name,href])=>{const Icon=icons[name]; return <Link key={name} href={href} onClick={()=>{setActive(name);setMobileOpen(false)}} className={`menu-item w-full flex items-center gap-3 px-3 py-2.5 text-sm ${active===name?'active':'text-slate-400'}`}><Icon size={16}/><span className="truncate">{name}</span>{name.includes('Live')||name==='Pengguna Online'?<span className="ml-auto text-[9px] rounded bg-emerald-500/10 px-1.5 py-0.5 text-emerald-400">LIVE</span>:null}</Link>})}</div>}</div>)}</nav><div className="sticky bottom-0 p-3 bg-[#061426]"><div className="rounded-xl border border-[#174052] bg-[#071a2b] p-3"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-full bg-[#12334a] text-cyan-300">R</div><div><div className="text-sm font-medium">RIZKY</div><div className="text-[10px] text-cyan-400">SUPER MASTER</div></div></div></div></div></aside>
    {mobileOpen&&<button aria-label="Close menu" onClick={()=>setMobileOpen(false)} className="fixed inset-0 z-30 bg-black/60 lg:hidden"/>}
    <main className="lg:ml-[276px] pt-16 min-h-screen"><div className="page-enter p-5 sm:p-7 lg:p-9 max-w-[1500px] mx-auto"><div className="mb-7 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-xs font-semibold tracking-[.2em] text-cyan-500">WORKSPACE</div><h1 className="mt-1 text-2xl sm:text-3xl font-bold tracking-tight">Dashboard Overview</h1><p className="mt-1 text-sm text-slate-500">Pusat akses seluruh fitur kerja D.KERJA.</p></div><div className="rounded-xl border border-[#183047] bg-[#08182a] px-4 py-2 text-xs text-slate-400">Status Sistem <span className="ml-2 text-emerald-400">● Online</span></div></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Modul Aktif','28','Modules'],['Aktivitas Hari Ini','48','Activities'],['Pengguna Online','08','Online'],['Status Sistem','100%','Healthy']].map(([a,b,c],i)=><div key={a} className="card-enter rounded-2xl border border-[#183047] bg-[#08182a] p-5" style={{animationDelay:`${i*70}ms`}}><div className="text-xs text-slate-500">{a}</div><div className="mt-3 text-2xl font-bold">{b}</div><div className="mt-1 text-[11px] text-cyan-500">{c}</div></div>)}</div><div className="mt-5 rounded-2xl border border-[#183047] bg-[#08182a] p-5 sm:p-6"><div><h2 className="font-semibold">Quick Access</h2><p className="mt-1 text-xs text-slate-500">Buka modul kerja secara langsung.</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{['Notes','AI Chat','Profil Bank','Alat Kerja'].map(name=><Link key={name} href={sections.flatMap(s=>s.items).find(x=>x[0]===name)?.[1]??'/'} className="menu-item flex items-center gap-3 border-[#183047] bg-[#071726] p-4"><div className="grid size-9 place-items-center rounded-lg border border-[#214258] bg-[#092235] text-cyan-400">{(()=>{const I=icons[name];return <I size={16}/>})()}</div><span className="text-sm font-medium">{name}</span></Link>)}</div></div></div></main>
  </div>
}