'use client'
import { useMemo, useState } from 'react'
import { Plus, Search, Trash2, Check, StickyNote } from 'lucide-react'

type Note={id:number;title:string;content:string}
export default function NotesWorkspace(){
 const [notes,setNotes]=useState<Note[]>([]),[title,setTitle]=useState(''),[content,setContent]=useState(''),[query,setQuery]=useState('')
 const filtered=useMemo(()=>notes.filter(n=>(n.title+' '+n.content).toLowerCase().includes(query.toLowerCase())),[notes,query])
 const add=()=>{if(!title.trim()&&!content.trim())return;setNotes(v=>[{id:Date.now(),title:title.trim()||'Catatan Baru',content:content.trim()},...v]);setTitle('');setContent('')}
 return <div className="grid gap-5 lg:grid-cols-[380px_1fr]"><section className="rounded-2xl border border-[#183047] bg-[#08182a] p-5"><div className="flex items-center gap-2 font-semibold"><StickyNote size={18} className="text-cyan-400"/> Catatan Baru</div><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Judul catatan" className="mt-5 w-full rounded-xl border border-[#183047] bg-[#071726] px-4 py-3 text-sm outline-none focus:border-cyan-800"/><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="Tulis catatan..." rows={8} className="mt-3 w-full resize-none rounded-xl border border-[#183047] bg-[#071726] px-4 py-3 text-sm outline-none focus:border-cyan-800"/><button onClick={add} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-cyan-800 bg-cyan-950/40 px-4 py-3 text-sm text-cyan-300 transition hover:bg-cyan-900/30"><Plus size={17}/> Simpan Catatan</button></section><section className="rounded-2xl border border-[#183047] bg-[#08182a] p-5"><div className="relative"><Search size={16} className="absolute left-3 top-3.5 text-slate-600"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari catatan..." className="w-full rounded-xl border border-[#183047] bg-[#071726] py-3 pl-10 pr-4 text-sm outline-none focus:border-cyan-800"/></div><div className="mt-4 space-y-3">{filtered.length===0?<div className="rounded-xl border border-dashed border-[#214258] p-8 text-center text-sm text-slate-600">Belum ada catatan.</div>:filtered.map(n=><article key={n.id} className="card-enter rounded-xl border border-[#183047] bg-[#071726] p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-medium">{n.title}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-500">{n.content||'Tidak ada isi.'}</p></div><button onClick={()=>setNotes(v=>v.filter(x=>x.id!==n.id))} className="rounded-lg p-2 text-slate-600 transition hover:bg-red-500/10 hover:text-red-400"><Trash2 size={16}/></button></div><div className="mt-3 flex items-center gap-1 text-[10px] text-emerald-500"><Check size={12}/> Tersimpan di sesi ini</div></article>)}</div></section></div>
}