'use client'

import Link from 'next/link'
import { ArrowLeft, CheckCircle2, Search, ShieldCheck, XCircle } from 'lucide-react'
import { useState } from 'react'

export default function ValidasiRekening(){
 const [bank,setBank]=useState(''); const [account,setAccount]=useState(''); const [result,setResult]=useState<'idle'|'valid'|'invalid'>('idle')
 const check=()=>{const clean=account.replace(/\D/g,'');setResult(bank&&clean.length>=6?'valid':'invalid')}
 return <main className="min-h-screen bg-[#040d18] p-5 text-slate-200 sm:p-8 lg:p-12"><div className="page-enter mx-auto max-w-3xl"><Link href="/" className="menu-item inline-flex items-center gap-2 px-3 py-2 text-sm text-slate-400"><ArrowLeft size={16}/> Kembali</Link><div className="mt-7"><div className="text-xs tracking-[.2em] text-cyan-500">D.KERJA / BANK & QRIS</div><h1 className="mt-2 text-3xl font-bold">Validasi Rekening</h1><p className="mt-2 text-sm text-slate-500">Validasi format rekening sebelum diproses lebih lanjut.</p></div><section className="mt-6 rounded-2xl border border-[#183047] bg-[#08182a] p-6"><div className="mb-5 flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl border border-cyan-900 bg-[#092235] text-cyan-400"><ShieldCheck size={21}/></div><div><div className="font-semibold">Pemeriksaan Rekening</div><div className="text-xs text-slate-600">Pemeriksaan lokal, tanpa mengirim data ke pihak ketiga.</div></div></div><label className="text-xs text-slate-500">Bank</label><select value={bank} onChange={e=>setBank(e.target.value)} className="mt-2 w-full rounded-xl border border-[#183047] bg-[#071726] px-4 py-3 text-sm outline-none focus:border-cyan-800"><option value="">Pilih bank</option><option>BCA</option><option>BNI</option><option>BRI</option><option>Mandiri</option><option>CIMB Niaga</option><option>Bank Jago</option><option>Lainnya</option></select><label className="mt-4 block text-xs text-slate-500">Nomor rekening</label><input inputMode="numeric" value={account} onChange={e=>setAccount(e.target.value)} placeholder="Masukkan nomor rekening" className="mt-2 w-full rounded-xl border border-[#183047] bg-[#071726] px-4 py-3 text-sm outline-none focus:border-cyan-800"/><button onClick={check} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl border border-cyan-800 bg-cyan-950/40 px-4 py-3 text-sm text-cyan-300 hover:bg-cyan-900/30"><Search size={17}/> Validasi</button>{result!=='idle'&&<div className={result==='valid'?'mt-4 rounded-xl border border-emerald-900 bg-emerald-950/20 p-4 text-sm text-emerald-300':'mt-4 rounded-xl border border-red-900 bg-red-950/20 p-4 text-sm text-red-300'}>{result==='valid'?<><CheckCircle2 className="mr-2 inline" size={17}/>Format rekening terlihat valid. Ini bukan verifikasi kepemilikan rekening.</>:<><XCircle className="mr-2 inline" size={17}/>Pilih bank dan masukkan nomor rekening yang cukup panjang.</>}</div>}</section></div></main>
}